application/users/routes.py
from flask import (render_template, request,
                   redirect, url_for, session,
                   flash, Blueprint, g)
from application.users.forms import UserForm, DeleteForm, EmptyForm
from application.models import User
from application import db, bcrypt
import datetime
from sqlalchemy.exc import IntegrityError
from decorators import (ensure_authenticated,
                        prevent_login_signup,
                        ensure_correct_user)

users_bp = Blueprint(
    'users',
    __name__,
    template_folder='templates'
)


# users
@users_bp.route('/')
@ensure_authenticated
def index():
    date = datetime.datetime.now().strftime('%A, %b %d, %Y')
    delete_form = DeleteForm()
    return render_template('users/index.html',
                           users=User.query.all(),
                           delete_form=delete_form,
                           date=date)


# user signup
@users_bp.route('/', methods=['POST'])
@prevent_login_signup
def signup():
    form = UserForm(request.form)
    if form.validate():
        try:
            new_user = User(form.username.data,
                            form.password.data,
                            datetime.datetime.now())
            db.session.add(new_user)
            db.session.commit()
            session['user_id'] = new_user.id
            flash('User Created!', 'positive')
            return redirect(url_for('users.index'))
        except IntegrityError:
            return render_template('users/new.html', form=form)
        return render_template('users/new.html', form=form)


# users new
@users_bp.route('/new')
@prevent_login_signup
def new():
    user_form = UserForm()
    return render_template('users/new.html', form=user_form)


# users edit
@users_bp.route('/<int:user_id>/edit')
@ensure_authenticated
@ensure_correct_user
def edit(user_id):
    found_user = User.query.get(user_id)
    user_form = UserForm(obj=found_user)
    return render_template('users/edit.html', user=found_user, form=user_form)


# users show
@users_bp.route('/<int:user_id>', methods=['GET', 'PATCH', 'DELETE'])
@ensure_authenticated
def show(user_id):
    empty_form = EmptyForm()
    found_user = User.query.get(user_id)
    delete_form = DeleteForm()
    if request.method == b'PATCH':
        form = UserForm(request.form)
        if form.validate():
            found_user.username = form.username.data
            found_user.password = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
            db.session.add(found_user)
            db.session.commit()
            flash('User Updated!', 'positive')
            return redirect(url_for('users.index'))
        return render_template('users/edit.html', user=found_user, form=form)
    if request.method == b'DELETE':
        delete_form = DeleteForm(request.form)
        if delete_form.validate():
            db.session.delete(found_user)
            db.session.commit()
            session.pop('user_id')
            flash('User Deleted!', 'positive')
        return redirect(url_for('auth.login'))
    return render_template('users/show.html',
                           user=found_user,
                           empty_form=empty_form,
                           delete_form=delete_form)


# follow and unfollow routes
@users_bp.route('/follow/<int:user_id>', methods=['POST'])
@ensure_authenticated
def follow(user_id):
    form = EmptyForm()
    curr_user_obj = g.user
    found_user = User.query.get(user_id)
    if form.validate_on_submit():
        if found_user is None:
            flash('User not found!', 'negative')
            return redirect(url_for('users.index'))
        if found_user == curr_user_obj:
            flash('You cannot follow yourself!')
            return redirect(url_for('users.show', user_id=found_user.id))
        curr_user_obj.follow(found_user)
        db.session.commit()
        flash(f'You are following {found_user.username}!', 'positive')
        return redirect(url_for('users.show', user_id=found_user.id))
    else:
        return redirect(url_for('users.index'))


@users_bp.route('/unfollow/<int:user_id>', methods=['POST'])
@ensure_authenticated
def unfollow(user_id):
    form = EmptyForm()
    found_user = User.query.get(user_id)
    curr_user_obj = g.user
    if form.validate_on_submit():
        if found_user is None:
            flash('User not found!', 'negative')
            return redirect(url_for('users.index'))
        if found_user == curr_user_obj:
            flash('You cannot unfollow yourself!', 'negative')
            return redirect(url_for('users.show', user_id=found_user.id))
        curr_user_obj.unfollow(found_user)
        db.session.commit()
        flash(f'You are not following {found_user.username}!', 'negative')
        return redirect(url_for('users.show', user_id=found_user.id))
    else:
        return redirect(url_for('users.index'))

application/templates/about.html
{% extends "base.html" %}

{% block title %}About page{% endblock %}

{% block content %}

    <br>
    <br>
    <br>
    <div class="ui four column grid">
        <div class="two column row">
            <div class="column"></div>
        </div>
        <div class="column"><img class="ui circular medium image" src="/static/js.png"></div>
        <div class="column"><img class="ui circular medium image" src="/static/flask.png"></div>
        <div class="column"><img class="ui circular medium image" src="/static/jinja.jpg"></div>
        <div class="column"><img class="ui circular medium image" src="/static/semantic-ui.svg"></div>
    </div>
    <h2 style="text-align: center">This project was built with Python Flask, Jinja2, SemanticUI and a bit of vanilla JavaScript.</h2>
    <h4 style="text-align: center"><a href="rafaelopez.com">Rafael Lopez</a> - Analytics, Data and Development.</h4>

{% endblock %}

application/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Note-Taking App - {% block title %}{% endblock %}</title>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
    <body>
        <nav>
            <ul>
                <li><a href="{{ url_for('users.index')}}" class="logo"><i class="pencil alternate icon"></i>Note-Taking App</a></li>
                {% if g.user.username %}
                    <li><a href="{{ url_for('auth.logout')}}">Sign out</a></li>
                    <li><a href="{{url_for('users.show', user_id=g.user.id)}}">Profile</a></li>
                {% else %}
                    <li><a href="{{ url_for('auth.login')}}">Login</a></li>
                {% endif %}
                <li><a href="{{ url_for('users.index')}}">Friends</a></li>
                <li><a href="{{ url_for('auth.about')}}">About</a></li>
            </ul>
        </nav>
        <br>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, msg in messages %}

                <div class="ui {{ category }} message compact">
                    <i class="close icon"></i>
                    <div class="header centered">
                        {{ msg }}
                    </div>
                </div>

                {% endfor %}
            {% endif %}
        {% endwith %}


        {% block content %}
        {% endblock %}
    <script type=text/javascript src="{{url_for('static', filename='scripts.js') }}"></script>
    </body>
</html>

application/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
    
    <div class="ui two column centered grid">
        <div class="column"><div class="ui segment">
            <h2 class="ui left floated header"><i class="pencil alternate icon"></i>Login</h2>
            <div class="ui clearing divider"></div>
            <p>New to the app? <a href="{{ url_for('users.new') }}">Create an account</a></p>

            <form class="ui form" method="POST" action="{{url_for('login')}}">
                {{ form.hidden_tag() }}
                {% for field in form if field.widget.input_type != 'hidden' %}
                    <div class="field">
                        {{field.label}}
                        {{field}}
                        <span>
                            {% if field.errors %}
                                {% for error in field.errors %}
                                {{ error }}
                                {% endfor %}
                            {% endif %}
                        </span>
                    </div>
                {% endfor %}
                <button class="ui button" type="submit">Login</button>
            </form>
        </div>
    </div>

{% endblock %}