application/notes/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators


class NoteForm(FlaskForm):
    title = StringField('Title', [validators.DataRequired()])
    note_body = StringField('Note Body', [validators.DataRequired()])


class DeleteForm(FlaskForm):
    pass

application/notes/routes.py
from flask import (render_template, request,
                   redirect, url_for, Blueprint)
from application.notes.forms import NoteForm, DeleteForm
from application.models import User, Note
from application import db
import datetime
from decorators import ensure_authenticated, ensure_correct_user

notes_bp = Blueprint(
    'notes',
    __name__,
    template_folder='templates'
)


# notes index
@notes_bp.route('/', methods=['GET', 'POST'])
@ensure_authenticated
def index(user_id):
    date = datetime.datetime.now().strftime('%A, %b %d, %Y')
    delete_form = DeleteForm()
    found_user = User.query.get(user_id)
    if request.method == 'POST':
        form = NoteForm(request.form)
        if form.validate():
            new_notes = Note(request.form['title'], datetime.datetime.now(),
                             request.form['note_body'], user_id)
            db.session.add(new_notes)
            db.session.commit()
            return redirect(url_for('notes.index', user_id=user_id))
        else:
            return render_template('notes/new.html', form=form)
    return render_template('notes/index.html', user=found_user,
                           delete_form=delete_form, date=date)


# notes new
@notes_bp.route('/new', methods=['GET', 'POST'])
@ensure_authenticated
@ensure_correct_user
def new(user_id):
    found_user = User.query.get(user_id)
    note_form = NoteForm()
    return render_template('notes/new.html', user=found_user, form=note_form)


# notes edit
@notes_bp.route('/<int:id>/edit')
@ensure_authenticated
@ensure_correct_user
def edit(user_id, id):
    found_note = Note.query.get(id)
    note_form = NoteForm(obj=found_note)
    return render_template('notes/edit.html', note=found_note, form=note_form)


# notes show
@notes_bp.route('/<int:id>',  methods=['GET', 'PATCH', 'DELETE'])
@ensure_authenticated
@ensure_correct_user
def show(user_id, id):
    found_note = Note.query.get(id)
    found_user = User.query.get(user_id)
    if request.method == b"PATCH":
        found_note.title = request.form["title"]
        found_note.note_body = request.form["note_body"]
        db.session.add(found_note)
        db.session.commit()
        return redirect(url_for('notes.index', user_id=user_id))
    if request.method == b"DELETE":
        delete_form = DeleteForm(request.form)
        if delete_form.validate():
            db.session.delete(found_note)
            db.session.commit()
        return redirect(url_for('notes.index', user_id=user_id))
    return render_template('notes/show.html', note=found_note, user=found_user)

application/notes/templates/notes/edit.html
{% extends "base.html" %}

{% block title %}Edit a note{% endblock %}

{% block content %}

    <div class="ui two column centered grid">
        <div class="column"><div class="ui segment">
            <h2 class="ui left floated header"><i class="pencil alternate icon"></i>Edit Note</h2>
            <div class="ui clearing divider"></div>
            <p>What are you thinking today?</p>

            <form class="ui form" method="POST" action="{{ url_for('notes.show', user_id=note.user_id, id=note.id) }}?_method=PATCH">
                {{ form.hidden_tag() }}
                {% for field in form if field.widget.input_type != 'hidden' %}
                    <div class="field">
                        {{field.label}}
                        {{field}}
                        <span>
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                            {% endif %}
                        </span>
                    </div>
                {% endfor %}
                <button class="ui button" type="submit">Save</button>
            </form>
        </div>
    </div>

{% endblock %}

application/notes/templates/notes/index.html
{% extends "base.html" %}

{% block title %}Notes Homepage{% endblock %}

{% block content %}

<div class="ui center aligned icon header">
    <i class="pencil alternate icon"></i>
    {% if g.user.id == user.id %}
        <h1>Hi {{g.user.username}}! These are your current notes.</h1>
    {% else %}
        <h1>Hi {{g.user.username}}! These are {{user.username}}'s notes.</h1>
    {% endif %}

<p>{{ date }} - <span id="clock"></span></p>
<a href="{{ url_for('notes.new', user_id=user.id) }}">Add Note</a>
</div>
  
<div class="ui divider"></div>

<div class="ui four column grid centered">

    {% for note in user.notes %} 

        <div class="column">
            <div class="ui centered cards">
                <div class="card">
                    <div class="content">
                        <img class="right floated mini ui image" src="/static/matthew.png">
                        <div class="header">
                            <a href="{{url_for('notes.show', user_id=user.id, id=note.id)}}">{{note.title}}</a>
                        </div>
                        <div class="meta">
                            {{note.date.strftime('%Y-%m-%d') }}
                        </div>
                        <div class="description">
                            {{note.note_body}}
                        </div>
                    </div>
                    <div class="extra content">
                        <div class="ui two buttons">
                            <div class="ui basic blue button"><a href="{{ url_for('notes.edit', user_id=user.id, id=note.id) }}">Edit</a></div>
                            <div class="ui basic red button"><form action="{{url_for('notes.show', user_id=user.id, id=note.id)}}?_method=DELETE" method="POST">
                                {{delete_form.hidden_tag()}}
                                <input type="submit" value="Delete">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %} 
</div>

{% endblock %}

application/notes/templates/notes/new.html
{% extends "base.html" %}

{% block title %}Add a note{% endblock %}

{% block content %}
    
<div class="ui two column centered grid">
    <div class="column"><div class="ui segment">
        <h2 class="ui left floated header"><i class="pencil alternate icon"></i>Add Note</h2>
        <div class="ui clearing divider"></div>
        <p>What are you thinking today?{{user.id}}||||{{g.user.id}}||{{session['user_id']}}</p>

        <form class="ui form" method="POST" action="{{ url_for('notes.index', user_id=user.id) }}">
            {{ form.hidden_tag() }}
            {% for field in form if field.widget.input_type != 'hidden' %}
                <div class="field">
                    {{field.label}}
                    {{field}}
                    <span>
                        {% if field.errors %}
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                        {% endif %}
                    </span>
                </div>
            {% endfor %}
            <button class="ui button" type="submit">Save</button>
        </form>
    </div>
</div>

{% endblock %}

application/notes/templates/notes/show.html
{% extends "base.html" %}

{% block title %}Note page.{% endblock %}

{% block content %}

    <div class="ui two column centered grid">
        <div class="column"><div class="ui segment">
            <h2 class="ui left floated header">{{ note.id }}. {{ note.user_id }}.{{ note.title }}</h2>
            <div class="ui clearing divider"></div>
            <h5>Written on {{ note.date }}</h5>
            <p>{{ note.note_body }}</p>
            <a href="{{ url_for('notes.index', user_id=user.id) }}">See all the notes.</a>
            <br>
            <button class="ui button"><a href="{{ url_for('notes.edit', user_id=user.id, id=note.id) }}">Edit Note</a></button>

        </div>
    </div>

{% endblock %}